#cloud-config

packages:
    - python
    - python-pip

runcmd:
    - pip install Flask
    - pip install wget
    - /usr/bin/jobflow-run.sh
    - echo "* * * * * root /usr/bin/jobflow-run.sh" >> /etc/cron.d/jobflow

write_files:
    - permissions: '0644'
      content: "contentS:jobflow_receiver.py"
      path: /usr/bin/jobflow_receiver.py
    
    - permissions: '0644'
      content: "contentS:ndimCollector.py"
      path: /usr/bin/ndimCollector.py
    
    - permissions: '0644'
      content: "contentS:jobflow_executor.py"
      path: /usr/bin/jobflow_executor.py

    - permissions: '0644'
      content: "contentS:jobflow_forwarder.py"
      path: /usr/bin/jobflow_forwarder.py
    
    - permissions: '0744'
      content: "contentS:jobflow-run.sh"
      path: /usr/bin/jobflow-run.sh

    - permissions: '0644'
      content: "contentT:occo_jobflow-config-sys.yaml"
      path: /etc/jobflow-config-sys.yaml
