
wfid: unique-id-of-the-wf
inputs:
    -
        name: one_file
        content: |
            lorem ipsum
            dolor
    -
        name: two_file
        content: |
            sit amet
            luna

