
wfid: unique-id-of-the-wf2
inputs:
    -
        name: one_file
        content: |
            one: lorem ipsum
            one: dolor
    -
        name: two_file
        content: |
            two: sit amet
            two: luna

