 
executable:
    filename: exe.bin
    tgzURL: http://mishra.lpds.sztaki.hu/edgidemo/download/jobflow/jobflow-app1.tgz
inputs:
    -
        name: one_file
    -
        name: two_file
outputs:
    -
        name: out_file
        targetname: one_file
        targeturl: http://192.168.153.153:5001/jobflow
    -
        name: out_file
        targetname: two_file
        targeturl: http://192.168.153.153:5001/jobflow
arguments: one_file two_file out_file          

