
wfid: unique-id-of-the-wf7
inputs:
    -
        name: one_file
        url: http://mishra.lpds.sztaki.hu/edgidemo/download/jobflow/file1.txt
    -
        name: two_file
        url: http://mishra.lpds.sztaki.hu/edgidemo/download/jobflow/file2.txt

