
sleepinterval: 5
jobdirroot: /tmp/jobflow/jobs/
listeningport: 5000
appconfigpath: /etc/jobflow-config-app.yaml

jobdirroot-collector: /tmp/jobflow/results/
listeningport-collector: 5001

logging:
    version: 1
    root:
        level: DEBUG
        handlers: [console]
    formatters:
        simpleFormatter:
            format: "%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s"
            #datefmt: '%Y-%m-%d %H:%M:%S.%f'

    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormatter
            level: DEBUG
            stream: ext://sys.stdout
        file-jobflow-receiver:
            class : logging.FileHandler
            formatter: simpleFormatter
            mode: w
            level: DEBUG
            filename: /var/log/jobflow/jobflow-receiver.log
        file-jobflow-executor:
            class : logging.FileHandler
            formatter: simpleFormatter
            mode: w
            level: DEBUG
            filename: /var/log/jobflow/jobflow-executor.log
        file-jobflow-forwarder:
            class : logging.FileHandler
            formatter: simpleFormatter
            mode: w
            level: DEBUG
            filename: /var/log/jobflow/jobflow-forwarder.log


    loggers:
        jobflow.receiver:
            propagate: false
            level: DEBUG
            handlers: [file-jobflow-receiver]
        jobflow.executor:
            propagate: false
            level: DEBUG
            handlers: [file-jobflow-executor]
        jobflow.forwarder:
            propagate: false
            level: DEBUG
            handlers: [file-jobflow-forwarder]

