
wfid: unique-id-of-the-wf7
inputs:
    -
        name: one_file
        content: |
            one: lorem ipsum
            one: dolor
    -
        name: two_file
        tgzURL: 
        content: |
            two: sit amet
            two: luna

