- permissions: '0644'
  content: |
        executable:
            filename: {{variables.jobflow.app.exe.filename}}
            tgzURL: {{variables.jobflow.app.exe.tgzurl}}
        inputs: {% for item in variables.jobflow.app.in %}
            -
                name: {{item.name}} {% if item.collector is defined %}
                collector: {{item.collector}} {% endif %} {% if item.format is defined %}
                format: {{item.format}} {% endif %} {% endfor %}
        outputs: {% for item in variables.jobflow.app.out %}
            -
                name: {{item.name}} {% if item.filter is defined %}
                filter: {{item.filter}} {% endif %}
                targetname: {{item.targetname}} {% if item.distribution is defined %}
                distribution: {{item.distribution}} {% endif %}
                targetip  : {% if item.targetnode is defined %}{{getipall(item.targetnode)}}{% else %}{{item.targetip}}{% endif %}
                targetport: {{variables.jobflow_global.receiver_port}} {% endfor %}
        arguments: {{variables.jobflow.app.args}}
  path: /etc/jobflow-config-app.yaml
