#cloud-config

packages:
    - python
    - python-pip

runcmd:
    - pip install Flask
    - /home/jobflow/jobflow-run.sh

write_files:
    - permissions: '0644'
      content: "content:jobflow_receiver.py"
      path: /home/jobflow/jobflow_receiver.py
    
    - permissions: '0644'
      content: "content:jobflow_executor.py"
      path: /home/jobflow/jobflow_executor.py

    - permissions: '0644'
      content: "content:jobflow_forwarder.py"
      path: /home/jobflow/jobflow_forwarder.py
    
    - permissions: '0744'
      content: "content:jobflow-run.sh"
      path: /home/jobflow/jobflow-run.sh

    - permissions: '0644'
      content: "content:jobflow-config-sys.yaml"
      path: /etc/jobflow-config-sys.yaml

    - permissions: '0644'
      content: "content:jobflow-config-app.yaml"
      path: /etc/jobflow-config-app.yaml




